### PR TITLE
Feature/mobile-ux-improvements

### LINKED ISSUE #62: [Feature]: Improve mobile UX
see title

### PR DESCRIPTION
**Pull request by RihanArfan**
Improves responsiveness. This PR doesn't close #62 since navigation will be replaced on mobile as per new scope.

### CODE REVIEW

**Comment by JamesHawkinss** [comment]
@RihanArfan Thanks for the PR! Will review soon. Can you please change to merge into dev?

**Comment by mrjvs** [comment]
Will review in a couple hours.

Do note: the scope of #62 was expanded, I just hadn't updated it yet. So this pr won't close the issue.

**Comment by RihanArfan** [comment]
I've updated the PR description to stop it closing the issue and changed the base branch to dev.

**Review by mrjvs — APPROVED** [review]
lgtm

**Pull request merged**
